### PR TITLE
Fix #114: UK addresses with no locality

### LINKED ISSUE #114: Workaround required for UK addresses where `locality` is not provided in Google API response, but `postal_town` is instead
I'm using this package exclusively with UK addresses, and have been finding that if you select any UK address smaller than a Town/City in a Form, then the `locality` component of the form widget will be empty (as it looks like Google API response has the `locality` under the `postal_town` type instead)

This means when the form (and then the Address field itself) is saved, even though all the Country, State, Lat/Long data is present, only the raw value is saved (will fall into the `if` here https://github.com/furious-luke/django-address/blob/e251edb9c7d10aeec1bc5d5cd500c19dee44102f/address/models.py#L51)

Would be good to have something similar to #55 eg.
```
if not locality and postal_town:
    locality = postal_town
```

and I assume a small change to `address.js` too.

Happy to do a PR for this myself if requested?

#### The town itself. This will save all data as expected
```
"result" : {
      "address_components" : [
         {
            "long_name" : "Royal Leamington Spa",
            "short_name" : "Royal Leamington Spa",
            "types" : [ "locality", "political" ]
         },
         {
            "long_name" : "Warwickshire",
            "short_name" : "Warwickshire",
            "types" : [ "administrative_area_level_2", "political" ]
         },
         {
            "long_name" : "England",
            "short_name" : "England",
            "types" : [ "administrative_area_level_1", "political" ]
         },
         {
            "long_name" : "United Kingdom",
            "short_name" : "GB",
            "types" : [ "country", "political" ]
         }
      ],
      "adr_address" : "\u003cspan class=\"extended-address\"\u003eRoyal Leamington Spa\u003c/span\u003e, \u003cspan class=\"country-name\"\u003eUK\u003c/span\u003e",
      "formatted_address" : "Royal Leamington Spa, UK",
      "geometry" : {
         "location" : {
            "lat" : 52.28519050000001,
            "lng" : -1.5200789
         },
         "viewport" : {
            "northeast" : {
               "lat" : 52.3143077,
               "lng" : -1.4930289
            },
            "southwest" : {
               "lat" : 52.2565389,
               "lng" : -1.56145
            }
         }
      },
      "icon" : "https://maps.gstatic.com/mapfiles/place_api/icons/geocode-71.png",
      "id" : "dfd1fd851dbb31541b5c37604c9f4c38402ee5bf",
      "name" : "Royal Leamington Spa",
      "place_id" : "ChIJh6XI-DQxd0gR47pPYF7_WMU",
      "reference" : "ChIJh6XI-DQxd0gR47pPYF7_WMU",
      "scope" : "GOOGLE",
      "types" : [ "locality", "political" ],
      "url" : "https://maps.google.com/?q=Royal+Leamington+Spa,+UK&ftid=0x48773134f8c8a587:0xc558ff5e604fbae3",
      "utc_offset" : 60,
      "vicinity" : "Royal Leamington Spa"
   },
```

#### A street within Leamington Spa. This will display fine in the form widget, but when the address is saved, only the raw value will be stored - note `Leamington Spa` appears as `postal_town` instead of `locality`
```
"result" : {
      "address_components" : [
         {
            "long_name" : "High Street",
            "short_name" : "High St",
            "types" : [ "route" ]
         },
         {
            "long_name" : "Leamington Spa",
            "short_name" : "Leamington Spa",
            "types" : [ "postal_town" ]
         },
         {
            "long_name" : "Warwickshire",
            "short_name" : "Warwickshire",
            "types" : [ "administrative_area_level_2", "political" ]
         },
         {
            "long_name" : "England",
            "short_name" : "England",
            "types" : [ "administrative_area_level_1", "political" ]
         },
         {
            "long_name" : "United Kingdom",
            "short_name" : "GB",
            "types" : [ "country", "political" ]
         },
         {
            "long_name" : "CV31",
            "short_name" : "CV31",
            "types" : [ "postal_code_prefix", "postal_code" ]
         }
      ],
      "adr_address" : "\u003cspan class=\"street-address\"\u003eHigh Street\u003c/span\u003e, \u003cspan class=\"extended-address\"\u003eRoyal Leamington Spa\u003c/span\u003e, \u003cspan class=\"locality\"\u003eLeamington Spa\u003c/span\u003e \u003cspan class=\"postal-code\"\u003eCV31\u003c/span\u003e, \u003cspan class=\"country-name\"\u003eUK\u003c/span\u003e",
      "formatted_address" : "High St, Royal Leamington Spa, Leamington Spa CV31, UK",
      "geometry" : {
         "location" : {
            "lat" : 52.2841804,
            "lng" : -1.5321367
         },
         "viewport" : {
            "northeast" : {
               "lat" : 52.2855293802915,
               "lng" : -1.530787719708498
            },
            "southwest" : {
               "lat" : 52.2828314197085,
               "lng" : -1.533485680291502
            }
         }
      },
      "icon" : "https://maps.gstatic.com/mapfiles/place_api/icons/geocode-71.png",
      "id" : "32e00b7543a9281b0a09272abb0f70cb61d95b27",
      "name" : "High Street",
      "place_id" : "EjZIaWdoIFN0LCBSb3lhbCBMZWFtaW5ndG9uIFNwYSwgTGVhbWluZ3RvbiBTcGEgQ1YzMSwgVUsiLiosChQKEgnhTf5okjR3SBHLhDl26r_GHBIUChIJqZHHQhE7WgIReiWIMkOg-MQ",
      "reference" : "EjZIaWdoIFN0LCBSb3lhbCBMZWFtaW5ndG9uIFNwYSwgTGVhbWluZ3RvbiBTcGEgQ1YzMSwgVUsiLiosChQKEgnhTf5okjR3SBHLhDl26r_GHBIUChIJqZHHQhE7WgIReiWIMkOg-MQ",
      "scope" : "GOOGLE",
      "types" : [ "route" ],
      "url" : "https://maps.google.com/?q=High+St,+Royal+Leamington+Spa,+Leamington+Spa+CV31,+UK&ftid=0x4877349268fe4de1:0x1cc6bfea763984cb",
      "utc_offset" : 60
   }
```

### PR DESCRIPTION
**Pull request by max-nicholson**
As part of the fix, I've had to modify jquery.geocomplete.min.js to add `"postal_town"` to `componentTypes`, as without doing this the `postal_town` in the Google API response won't be saved to the widget - this is a known limitation of the plugin - https://github.com/ubilabs/geocomplete/issues/335

`componentTypes` is a private property of the plugin, so I couldn't find a way to modify it without modifying the source code directly, but as the repo is archived and unmaintained this seemed like an acceptable solution to me.

In theory if this isn't acceptable, we could potentially look at extending the `initDetails` method of the plugin (https://github.com/ubilabs/geocomplete/blob/7ce2f83ac4b621b6816f85eaede8f03595e58c9a/jquery.geocomplete.js#L257) and add the updating of the `postal_town` component, but this seemed much more involved of a change (and not 100% sure it would be possible either).

### CODE REVIEW

**Comment by banagale** [comment]
First, thanks for doing this and for the test.

I loaded this and was able to run the test successfully.

Just in case, I went to try to submit the test address given in the raw of the test data using the form in the example app.  In that case it appears that the js may not be returning the complete dict for the geocoded info from google maps.  The result was an address created only with the raw still.

I tried Oxford, UK and Portland, OR and those did come back with full dicts.  Would you please double check my test of this using the example site's form?

**Comment by max-nicholson** [comment]
I've run some more tests with UK addresses to double check and the full dicts were populated (using the `postal_town` as the `locality` as I'd hope). 

I then switched back to `develop` branch and retried the same raw addresses, and only got the raw field populated.

Lines in yellow done on `develop` branch using the example_site, white lines done on this feature branch. Note the UK addresses that worked in yellow were at the city level (ie. Oxford, UK and Leamington Spa, UK) - and on my feature branch no new address was created for those as the address ended up being the same

image

Maybe you were using a cached (unchanged) version of the JS if you hadn't done a hard reload before trying the feature branch? Otherwise I'm not sure why the change isn't working for you

**Comment by banagale** [comment]
@max-nicholson First, thank you for having another look. I'm ready to accept this PR.

I did think it might be my cache, so I tried it again and inspected sources to be sure I was running the updated JS and I was.

It took me a bit but I believe I've identified a bug (at least in chrome) where in some cases if you can lose the geocoded data that `address.js` hides in `#address-compontents`.

The bug appears to be independent of your change and affects all addresses.  To repro:

 - Load example site with valid google maps api key
 - Start typing in an address, hit enter to select the top-most highlighted autocomplete
 - Click on the page but not on the submit button

--> Intermittently the data is erased from the name attributes.

This is a whole extra ask, but would you mind trying to repro this bug?  I'm including two screen recordings that show the behavior. I'll accept this regardless, but if you can also see this happening, I'll also file an issue to handle this.

Rob

**Comment by banagale** [comment]
I went ahead and merged this and created a new issue, #118 to encapsulate the bug I think I found.

I labeled it Needs Validation, so if you have time to repro that, we can at least know it is a real to-do.

Thanks again for this.

**Pull request merged**
