### PR TITLE
remove python_2_unicode_compatible that no longer exists in django 3

### LINKED ISSUE #91: Does django-address works with Django 3.0.2?
Does django-address works with Django 3?  I getting the following error when makemigration:
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\pei_l\Documents\Projects\django\wmtennis\env\lib\site-packages\django\core\management\__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "C:\Users\pei_l\Documents\Projects\django\wmtennis\env\lib\site-packages\django\core\management\__init__.py", line 377, in execute
    django.setup()
  File "C:\Users\pei_l\Documents\Projects\django\wmtennis\env\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\pei_l\Documents\Projects\django\wmtennis\env\lib\site-packages\django\apps\registry.py", line 114, in populate
    app_config.import_models()
  File "C:\Users\pei_l\Documents\Projects\django\wmtennis\env\lib\site-packages\django\apps\config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "C:\Users\pei_l\AppData\Local\Programs\Python\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\pei_l\Documents\Projects\django\wmtennis\env\lib\site-packages\address\models.py", line 7, in <module>
    from django.utils.encoding import python_2_unicode_compatible
ImportError: cannot import name 'python_2_unicode_compatible' from 'django.utils.encoding'

### PR DESCRIPTION
**Pull request by msarahan**
fixes #91

this arguably breaks python 2 in some ways.  I can spend a bit more time on this if you'd prefer to maintain python 2 support, even though it is beyond its supported lifetime.

### CODE REVIEW

**Comment by LifeMoroz** [comment]
We have to provide information in README for compatible versions.
Can you do it here?

**Comment by msarahan** [comment]
Yes, will do.  Thanks!

**Comment by moritz89** [comment]
Due to lack of activity, should I recreate a PR with an update to the README? This would probably result in a version bump from 0.2.1 to 0.3.0?

**Comment by msarahan** [comment]
My apologies.  I got sidetracked between a new job and all this COVID stuff.  I will push a commit momentarily.

**Comment by banagale** [comment]
I did not merge this because I wanted to make the commits individually. This was helpful, particularly the discussion on the version bump and compatibility.

In lieu of this pull, these commits handle the changes:
 - Remove deprecated python 2.7 support: 51a02df9f31d33ac8f84d15dc26c2884d01347f7
 - Update setup.py, bumping version and updating package classifiers to updated requirements as described [here](https://github.com/furious-luke/django-address/issues/98#issuecomment-626215196).

Many thanks to @msarahan, @moritz89 and @LifeMoroz for contributing to this PR.

**Pull request closed without merging**
