### PR TITLE
Unblock django 2.0 using compat.py pattern

### PR DESCRIPTION
**Pull request by klowe0100**
Hi. I recently had to upgrade to django 2.0 and pushed through a few issues. I'm up for spending some time to polish the changes more if you would like.

### CODE REVIEW

**Comment by wpf500** [comment]
This worked for me, thanks!

**Comment by karbassi** [comment]
Fixed in #78

**Comment by karbassi** [comment]
@furious-luke you can close this since it was fixed in #78

**Comment by banagale** [comment]
Closing as completed in #78.  Thank you @klowe0100

**Pull request closed without merging**
