### PR TITLE
Fix adding app to INSTALLED_APPS in README

### PR DESCRIPTION
**Pull request by frlan**

### CODE REVIEW

**Comment by banagale** [comment]
@frlan Thank you for this, Frank.

I've [already patched this](https://github.com/furious-luke/django-address/issues/108#issuecomment-631820760) and it will be fixed in the next release.

**Comment by frlan** [comment]
@banagale  Curious -- why is the fix not on master?

**Comment by banagale** [comment]
On May 24, 2020, at 1:54 PM, Frank Lanitz <notifications@github.com> wrote:

﻿

@banagale <https://github.com/banagale> Curious -- why is the fix not on
master?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/furious-luke/django-address/pull/110#issuecomment-633297887>,
or unsubscribe

**Comment by banagale** [comment]
@frlan Good question. Because this project uses ‘git flow’ style and it is at ‘HEAD‘ of ‘develop’. See the first bullet under “Project Notes” here: https://github.com/furious-luke/django-address/issues/98#issuecomment-626281195

For something as small but glaring as this I may push a minor release just to fix it. But I’m not there quite yet.

**Pull request closed without merging**
